language: java
jdk:
  - oraclejdk8

## export GPG details
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

## Deploy only tagged releases
deploy:
  provider: script
  script: "mvn clean deploy --settings .travis.settings.xml -DskipTests=true -P release -B"
  on:
    tags: true
    branch: releases
