language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: "ltPJfh8sJdBvfU+b+XQYGUSRU1ZfKAnNSSJ5/PutUcSFgzt30JvGZVeqJ+jVuXbQ8P97x8kUHisiDT8JsonwczAYX//jmqJxWpMAtOGngpBMr/wGYvjqbyA1CNy5nWLd7VB7VAOYGrcGc85838PJ6wYHb19a9ickEo+htVs6CyQQt2fxntw+7pJie9Jhl6SA4zKLqiXhj1qMwah+0m5tuPoQYwvaXPzQXHl6kd9AxhuOn4CxpIQIFQYQHSLkMlKiLmcjMTOBMidEiWy84z6sFWNcJj4iFgXG1/XkAhjHd4Ws22mGd/+pQoHzZO0/Uh+JbZo97AiEtlUCiOO2lcT6I4c0a7Jta0PWRz3i9NH7H5+JGa9WZYnEzrMxxdANlV69X/EUnqpNAvGFROA9mznkzk6rwdFZ/pTpW+SoVnSil3FcfOctuNjWVTQSR4CP2sK602yEQHX8yVfKOAB0zRYQuQMciwts1cPB8X3jj/nKPVWDcYLeF2FbdzIFyI3C71+z/Q0VbxoTjuQKtBztDXUiIRXKp3XY27QTOPukGKQ9z2yeAnUjZBzbcSUPVN3VHjVo26cHtkTzW02qrIcRxrfbujNDWRreyEKWewq+I3kV/tq2f0RKCKBHVBpP3FS6+KnN5ONqU9FqqEl/9V/GDRKXI2zZ5pfY9i6MDrQIfw+/9YQ="
    - secure: "PwXlBp6mwZ/JPsac4jvT8OjbvwLJgc1WhzdLn/wXWpA0ytTGJDe9BfUElJCbBuE+VfZnSH62WBofZCTBrQT1f7t8BP4XpR+F/OTPLOG4OmUIEiU+TRXmWA1CWAKvhTkFMyDGWVS3I7sLH95ImAsVzXjEpey1R2N7QMXKO8WXFJCWpu7d/b3rlSBT5IK4KYEpPbNY5d6VA/z826H8lU71tD+aigNwuOMwTQhEhU4Bg2TufbFGc36NTeU/q+ClelDfV4eykmPCRYB9ViFAC1XnxjDgSt4uWl40280S5CJl7+qW2s/sU52ARS9tbSgmWufcaYsmFQPP4RLJYR9l8Njf9PnWf6RFrUTsdwlF08IBrVri2xOP7SfjNJ+JD7VgVfhMN1Imx1QF+3GYze8O6FcfMXSJjRSLoLKXNp98VCTVqTIDOqZ9CYb9IQ7Ri19NoP2vncZZogrITNtB9ogVgvfPHvcb9Xm/DhT0PKiGjogkt+EzD6XoVFQpCpHvBGU1XtpTX1bSK18eS4olQM5i8nJ/3aOpoZJUaNAWUH3QdDv7gX7zmIEQn3unuUuGHnRLdg4GgC7Uq7PmIn3qVFrNw+ZniJfzWsgULmbXAYrofFpqA0OcP+Wnh+1u5ws1RYntlxBF/HCmwSoE4P51VwMxtaRZUR0YcdxWS8d3zlHdej9yZDw="

after_success:
  script: "mvn clean deploy -DskipTests=true --settings .travis.settings.xml"
  on:
    tags: true
